;;; test-mevedel-memory-review.el -- Sessionless consolidation requests -*- lexical-binding: t -*-

;;; Commentary:

;; Fake inference at gptel-request while retaining its real dry-run preparation.

;;; Code:

(require 'helpers
         (file-name-concat
          (file-name-directory
           (or buffer-file-name load-file-name byte-compile-current-file))
          "helpers"))
(require 'gptel-request)
(require 'gptel-openai)
(require 'gptel-anthropic)
(require 'gptel-bedrock)
(require 'mevedel-memory-scope)
(require 'mevedel-memory-review)
(require 'mevedel-memory-list)
(require 'mevedel-system)

(defconst mevedel-test-memory-review--none
  "## Promote\n- none\n## Update\n- none\n## Merge\n- none\n## Remove\n- none\n## Instructions\n- none\n## No action\n- No supported changes.")

(mevedel-deftest mevedel-memory-review-request
    (:vars* ((directory (make-temp-file "mevedel-memory-review-" t))
             (workspace (mevedel-workspace--create :root directory))
             (mevedel-memory-dirs nil)
             (gptel--known-backends nil)
             (model (make-symbol "review-model"))
             (backend (gptel-make-openai "review-test" :key "test-only" :models (list model)))
             (real-request (symbol-function 'gptel-request))
             (real-investigation-tools (symbol-function 'mevedel-memory-investigation-tools))
             (entries (list (list :id (make-string 64 ?a) :file "digest.md" :session "session"
                                  :created "2026-09-07T12:00:00Z" :body "## Done\n- Observed: Tests passed.")))
             (settlements 0) workload sent sent-system result handle request callback investigation)
     :before-each ((put model :context-window 128) (put model :capabilities '(tool-use)))
     :after-each ((when handle (funcall (plist-get handle :cancel)))
                  (delete-directory directory t)))
  (cl-letf (((symbol-function 'mevedel-model-resolve-workload)
             (lambda (kind &rest _) (setq workload kind) (list :backend backend :model model)))
            ((symbol-function 'mevedel-memory-investigation-tools)
             (lambda (state)
               (setq investigation state)
               (funcall real-investigation-tools state)))
            ((symbol-function 'gptel-request)
             (lambda (prompt &rest args)
               (let ((fsm (apply real-request prompt (plist-put (copy-sequence args) :dry-run t))))
                 (unless (plist-get args :dry-run)
                   (setq sent prompt sent-system (plist-get args :system)
                         request fsm callback (plist-get args :callback)))
                 fsm))))
    (cl-labels ((start (&rest options)
                  (setq handle
                        (apply #'mevedel-memory-review-request
                               (mevedel-memory-scope-capture workspace) entries
                               (lambda (value) (cl-incf settlements) (setq result value)) options)))
                (respond (text)
                  (funcall callback text (gptel-fsm-info request))))
      ,test))
  (test)
  :doc "uses the memory workload, scoped tools, and terminal validation without publishing coverage"
  (progn
    (start)
    (should (eq 'memory workload))
    (should sent)
    (should (string-match-p "64000 tokens and 262144 accounted bytes" sent-system))
    (should (string-match-p "64 tool calls and 65536 tool-result bytes" sent-system))
    (should (string-match-p "at most 32768 bytes" sent-system))
    (should (string-match-p "180 seconds" sent-system))
    (should-not (string-match-p "{{REVIEW_LIMITS}}" sent-system))
    (dolist (rule '("`user`:" "`feedback`:" "`project`:" "`reference`:"
                    "Tasks, blockers, deadlines, progress, and decisions belong"
                    "reviewing older notes containing project progress"
                    "No action is a successful"))
      (should (string-search rule sent-system)))
    (with-current-buffer (plist-get handle :buffer)
      (should-not mevedel--session)
      (should (equal '("Read" "Glob" "Grep") (mapcar #'gptel-tool-name gptel-tools))))
    (respond mevedel-test-memory-review--none)
    (respond t)
    (should-not result)
    (gptel--fsm-transition request 'DONE)
    (ert-info ((format "Review error: %s" (plist-get result :error)))
      (should (eq 'success (plist-get result :outcome))))
    (should (= 1 (length (plist-get result :entries))))
    (should-not (plist-get result :proposals))
    (should (equal mevedel-test-memory-review--none (plist-get result :reply)))
    (should-not (buffer-live-p (plist-get handle :buffer)))
    (should-not (file-exists-p (file-name-concat directory ".mevedel"))))
  :doc "Unicode evidence remains text through request admission and the inspectable buffer"
  (let ((body "## Learned\n- PostgreSQL \u2013 user correction; test \u754c condition."))
    (setf (plist-get (car entries) :body) body)
    (start)
    (ert-info ((format "Review error: %s" (plist-get result :error)))
      (should sent))
    (should (multibyte-string-p sent))
    (should (equal body (gethash "body" (aref (gethash "digests" (json-parse-string sent)) 0))))
    (with-current-buffer (plist-get handle :buffer)
      (should (string-match-p "PostgreSQL \u2013" (buffer-string))))
    (respond mevedel-test-memory-review--none)
    (gptel--fsm-transition request 'DONE)
    (should (eq 'success (plist-get result :outcome))))
  :doc "runs an admitted Read without inheriting interactive tool confirmation"
  (let ((gptel-confirm-tool-calls t) tool-result)
    (with-temp-file (file-name-concat directory "source.el") (insert ";; Source evidence.\n"))
    (start)
    ;; Stop the fake inference boundary after gptel has executed the real tool.
    (setf (gptel-fsm-handlers request) (copy-alist (gptel-fsm-handlers request)))
    (setf (alist-get 'TRET (gptel-fsm-handlers request))
          (list (lambda (fsm) (setq tool-result (plist-get (gptel-fsm-info fsm) :tool-result)))))
    (setf (plist-get (gptel-fsm-info request) :tool-use)
          (list (list :name "Read" :args '(:root "workspace" :path "source.el"))))
    (gptel--fsm-transition request 'TOOL)
    (should tool-result)
    (should (string-match-p "Source evidence" (nth 2 (car tool-result))))
    (should-not result)
    (respond mevedel-test-memory-review--none)
    (gptel--fsm-transition request 'DONE)
    (should (eq 'success (plist-get result :outcome)))
    (should (= 1 settlements)))
  :doc "rejects unavailable tool names before dispatch without entering an unbounded repair loop"
  (let (diagnostics)
    (start)
    (setf (gptel-fsm-handlers request) (copy-alist (gptel-fsm-handlers request)))
    (setf (alist-get 'TRET (gptel-fsm-handlers request)) (list #'ignore))
    (setf (plist-get (gptel-fsm-info request) :tool-use)
          (list (list :name "Bash" :args '(:command "true"))))
    (mevedel-test--with-captured-diagnostics diagnostics
      (gptel--fsm-transition request 'TOOL))
    (should (eq 'error (plist-get result :outcome)))
    (should (string-match-p "Unavailable review tool" (plist-get result :error)))
    (should (string-empty-p diagnostics))
    (should-not (buffer-live-p (plist-get handle :buffer))))
  :doc "cancellation and expired ownership settle once and reject late completion"
  (dolist (mode '(cancel expired))
    (let ((current t))
      (setq result nil settlements 0)
      (start :currentp (lambda () current))
      (if (eq mode 'cancel)
          (progn (funcall (plist-get handle :cancel)) (funcall (plist-get handle :cancel)))
        (setq current nil))
      (respond mevedel-test-memory-review--none)
      (gptel--fsm-transition request 'DONE)
      (should (eq (if (eq mode 'cancel) 'aborted 'error) (plist-get result :outcome)))
      (should (= 1 settlements))
      (should-not (buffer-live-p (plist-get handle :buffer)))))
  :doc "reports reasoning and reply charges independently of unavailable provider usage"
  (progn
    (start)
    (respond (cons 'reasoning (make-string 40 ?r)))
    (respond (make-string 100 ?x))
    (gptel--fsm-transition request 'DONE)
    (should (eq 'error (plist-get result :outcome)))
    (should (= 140 (plist-get result :output-bytes)))
    (should (= 40 (plist-get result :reasoning-bytes)))
    (should (= 100 (plist-get result :reply-bytes)))
    (should (= 0 (plist-get result :tool-call-bytes)))
    (should (= 0 (plist-get result :tool-call-count)))
    (should (= 1 (plist-get result :rounds)))
    (should (= 36 (plist-get result :output-estimated-tokens)))
    (should (= 0 (plist-get result :output-tokens))))
  :doc "malformed and oversized replies never become successful reviews"
  (dolist (reply (list "## Promote\n- none" (make-string 33000 ?x)))
    (setq result nil settlements 0)
    (start)
    (setf (plist-get (gptel-fsm-info request) :tokens) '(:input 100 :cached 20 :output 7000)
          (plist-get (gptel-fsm-info request) :stream) nil)
    (respond reply)
    (gptel--fsm-transition request 'DONE)
    (should (eq 'error (plist-get result :outcome)))
    (should (= 7000 (plist-get result :output-tokens)))
    (should (= (string-bytes reply) (plist-get result :output-bytes)))
    (when (> (length reply) 32000)
      (should (> (plist-get result :output-estimated-tokens) 8000))
      (should (eq 'proposal-bytes (plist-get result :budget-kind)))
      (should (= 32768 (plist-get result :output-limit))))
    (let ((snapshot (funcall (plist-get handle :usage))))
      (setf (plist-get snapshot :output-tokens) 0)
      (should (= 7000 (plist-get (funcall (plist-get handle :usage)) :output-tokens))))
    (should-not (plist-get result :proposals))
    (should (= 1 settlements))
    (should-not (buffer-live-p (plist-get handle :buffer))))
  :doc "admits a complete digest prefix and reports every omitted candidate"
  (progn
    (setq entries (list (car entries)
                        (list :id (make-string 64 ?b) :body (make-string 150000 ?x))
                        (list :id (make-string 64 ?c) :body "Later evidence.")))
    (start)
    (let* ((input (json-parse-string sent :object-type 'plist :array-type 'list))
           (digests (plist-get input :digests)))
      (should (= 1 (length digests)))
      (should (equal (plist-get (car entries) :body) (plist-get (car digests) :body)))
      (should (= 2 (plist-get input :omitted_digests))))
    (respond mevedel-test-memory-review--none)
    (gptel--fsm-transition request 'DONE)
    (should (eq 'success (plist-get result :outcome)))
    (should (equal (list (car entries)) (plist-get result :entries)))
    (should (= 2 (plist-get result :omitted-digests))))
  :doc "an oversized first digest fails before dispatch and empty batches require explicit memory-only admission"
  (progn
    (setf (plist-get (car entries) :body) (make-string 150000 ?x))
    (start)
    (should-not sent)
    (should (eq 'error (plist-get result :outcome)))
    (setq entries nil result nil)
    (start)
    (should-not sent)
    (should (eq 'error (plist-get result :outcome)))
    (setq result nil)
    (start :memory-only t)
    (should sent)
    (respond mevedel-test-memory-review--none)
    (gptel--fsm-transition request 'DONE)
    (should (eq 'success (plist-get result :outcome)))
    (should-not (plist-get result :entries)))
  :doc "checks the prepared payload at dispatch and rejects tool-expanded context before transport"
  (progn
    (start)
    (setf (plist-get (gptel-fsm-info request) :data)
          (plist-put (plist-get (gptel-fsm-info request) :data) :expanded (make-string 600000 ?x)))
    (gptel--fsm-transition request 'WAIT)
    (should (eq 'error (plist-get result :outcome)))
    (should (string-match-p "usable input context" (plist-get result :error)))
    (should-not (buffer-live-p (plist-get handle :buffer))))
  :doc "the running buffer shows admitted evidence and response and killing it cancels the review"
  (progn
    (start)
    (with-current-buffer (plist-get handle :buffer)
      (should buffer-read-only)
      (should (string-match-p "Observed: Tests passed" (buffer-string))))
    (respond "Inspecting the evidence.")
    (with-current-buffer (plist-get handle :buffer)
      (should (string-match-p "Inspecting the evidence" (buffer-string))))
    (kill-buffer (plist-get handle :buffer))
    (should (eq 'aborted (plist-get result :outcome)))
    (respond mevedel-test-memory-review--none)
    (gptel--fsm-transition request 'DONE)
    (should (= 1 settlements)))
  :doc "the running inspector separates evidence, follows response, and leaves the request alive on close"
  (save-window-excursion
    (start)
    (let ((source (plist-get handle :buffer)) inspector)
      (unwind-protect
          (cl-letf (((symbol-function 'mevedel-cockpit-surface-context)
                     (lambda (&rest _) (list :workspace workspace)))
                    ((symbol-function 'mevedel-memory-pass-running)
                     (lambda (_) (list :request handle))))
            (setq inspector (mevedel-memory-list-running))
            (with-current-buffer inspector
              (should (string-search "Model response" (buffer-string)))
              (should-not (string-search "Observed: Tests passed" (buffer-string)))
              (mevedel-report-previous)
              (should (string-search "Observed: Tests passed" (buffer-string)))
              (mevedel-report-next))
            (respond "Incoming exact response.")
            (sleep-for 0.2)
            (with-current-buffer inspector
              (should (string-search "Incoming exact response." (buffer-string)))
              (mevedel-report-refresh)
              (mevedel-report-refresh)
              (should (string-search "Incoming exact response." (buffer-string)))
              (mevedel-report-quit))
            (should (buffer-live-p source))
            (should-not result)
            (should-not (buffer-local-value 'after-change-functions source)))
        (when (buffer-live-p inspector) (kill-buffer inspector)))))
  :doc "the real deadline timer retires the request and late callbacks cannot revive it"
  (let ((timers (copy-sequence timer-list)))
    (start)
    (let ((added (cl-set-difference timer-list timers)))
      (should (= 1 (length added)))
      (let ((timeout (car added)))
        (should (<= 179 (float-time (time-subtract (timer--time timeout) (current-time))) 180))
        ;; Deliver the scheduled timeout now without waiting three minutes.
        (cancel-timer timeout)
        (timer-set-time timeout (current-time))
        (timer-activate timeout)
        (with-timeout (2 (ert-fail "Review timeout did not settle"))
          (while (not result) (accept-process-output nil 0.01)))
        (should-not (memq timeout timer-list))))
    (should (eq 'error (plist-get result :outcome)))
    (should (equal "Review timed out" (plist-get result :error)))
    (respond mevedel-test-memory-review--none)
    (gptel--fsm-transition request 'DONE)
    (should (= 1 settlements))
    (should-not (buffer-live-p (plist-get handle :buffer))))
  :doc "provider token usage and a sixty-fifth tool call each exhaust the whole review"
  (progn
    (start)
    (setf (plist-get (gptel-fsm-info request) :tokens) '(:input 100 :output 64001))
    (respond mevedel-test-memory-review--none)
    (respond t)
    (should (eq 'error (plist-get result :outcome)))
    (should (= 64001 (plist-get result :output-tokens)))
    (should (eq 'output-tokens (plist-get result :budget-kind)))
    (should (= 64000 (plist-get result :output-limit)))
    (setq result nil settlements 0)
    (with-temp-file (file-name-concat directory "source.el") (insert ";; Source.\n"))
    (start)
    (setf (gptel-fsm-handlers request) (copy-alist (gptel-fsm-handlers request)))
    (setf (alist-get 'TRET (gptel-fsm-handlers request)) (list #'ignore))
    (setf (plist-get (gptel-fsm-info request) :tool-use)
          (cl-loop repeat 65 collect (list :name "Read" :args '(:root "workspace" :path "source.el"))))
    (gptel--fsm-transition request 'TOOL)
    (should (eq 'error (plist-get result :outcome)))
    (should (equal "Tool call budget exhausted" (plist-get result :error)))
    (should (= 64 (plist-get result :tool-call-count)))
    (should (= 1 settlements))
    (should-not (buffer-live-p (plist-get handle :buffer))))
  :doc "reasoning beyond the old cumulative cap leaves room for a valid proposal reply"
  (progn
    (start)
    (respond (cons 'reasoning (make-string 33000 ?r)))
    (should-not result)
    (respond mevedel-test-memory-review--none)
    (gptel--fsm-transition request 'DONE)
    (should (eq 'success (plist-get result :outcome)))
    (should (> (plist-get result :output-bytes) 32768))
    (should (> (plist-get result :output-estimated-tokens) 8000))
    (should (= (string-bytes mevedel-test-memory-review--none) (plist-get result :result-bytes)))
    (should-not (plist-get result :budget-kind)))
  :doc "byte and Unicode token guards retain distinct thresholds and cumulative counters"
  (dolist (case '((262145 120 output-bytes 262144)
                  (21400 30028 output-estimated-tokens 64000)))
    (setq result nil settlements 0)
    (start)
    (let ((text (make-string (nth 0 case) (nth 1 case))))
      (respond (cons 'reasoning text))
      (should (eq 'error (plist-get result :outcome)))
      (should (eq (nth 2 case) (plist-get result :budget-kind)))
      (should (= (nth 3 case) (plist-get result :output-limit)))
      (should (= (string-bytes text) (plist-get result :output-bytes)))
      (should (= 0 (plist-get result :result-bytes)))
      (should (string-match-p (symbol-name (nth 2 case)) (plist-get result :error)))
      (respond "late")
      (should (= 1 settlements))))
  :doc "custom budgets are frozen and their exact boundaries are inclusive"
  (let ((mevedel-memory-review-max-tokens 100)
        (mevedel-memory-review-max-bytes 398))
    (start)
    (should (string-match-p "100 tokens and 398 accounted bytes" sent-system))
    (setq mevedel-memory-review-max-tokens 64000
          mevedel-memory-review-max-bytes 262144)
    (respond (make-string 398 ?x))
    (should-not result)
    (should (= 100 (plist-get (funcall (plist-get handle :usage)) :output-estimated-tokens)))
    (respond "x")
    (should (eq 'output-bytes (plist-get result :budget-kind)))
    (should (= 398 (plist-get result :output-limit)))
    (should (= 399 (plist-get result :result-bytes))))
  :doc "the final parser byte boundary is independent of the larger cumulative allowance"
  (dolist (size '(32768 32769))
    (setq result nil settlements 0)
    (start)
    (respond (cons 'reasoning (make-string 1000 ?r)))
    (respond (concat mevedel-test-memory-review--none
                     (make-string (- size (length mevedel-test-memory-review--none)) ?x)))
    (should-not result)
    (gptel--fsm-transition request 'DONE)
    (should (eq (if (= size 32768) 'success 'error) (plist-get result :outcome)))
    (should (= size (plist-get result :result-bytes)))
    (should (= (+ size 1000) (plist-get result :output-bytes)))
    (when (= size 32769)
      (should (eq 'proposal-bytes (plist-get result :budget-kind)))))
  :doc "followups clamp native provider limits to remaining reported or estimated usage"
  (dolist (reported '(9000 10))
    (setq result nil settlements 0)
    (start)
    (cl-letf (((symbol-function 'gptel--handle-wait) #'ignore))
      (gptel--fsm-transition request 'WAIT)
      (should (= 64000 (plist-get (plist-get (gptel-fsm-info request) :data) :max_output_tokens)))
      (setf (plist-get (gptel-fsm-info request) :tokens) (list :input 100 :output reported))
      (respond (cons 'reasoning (make-string 33000 ?r)))
      (respond "intermediate")
      (respond t)
      (let* ((snapshot (funcall (plist-get handle :usage)))
             (remaining (- 64000 (max reported (plist-get snapshot :output-estimated-tokens)))))
        (gptel--fsm-transition request 'WAIT)
        (should (= remaining (plist-get (plist-get (gptel-fsm-info request) :data) :max_output_tokens)))
        (should (= 0 (plist-get (funcall (plist-get handle :usage)) :result-bytes))))
      (setf (plist-get (gptel-fsm-info request) :tokens) '(:input 100 :output 100))
      (respond mevedel-test-memory-review--none)
      (respond t)
      (gptel--fsm-transition request 'DONE)
      (should (eq 'success (plist-get result :outcome)))
      (should (equal mevedel-test-memory-review--none (plist-get result :reply)))
      (should (= 2 (plist-get result :rounds)))
      (should (= 33000 (plist-get result :reasoning-bytes)))
      (should (= (+ (length "intermediate") (length mevedel-test-memory-review--none))
                 (plist-get result :reply-bytes)))
      (should (= (+ reported 100) (plist-get result :output-tokens)))))
  :doc "an exhausted budget stops a followup before transport and retains the exact threshold"
  (progn
    (start)
    (setf (plist-get (gptel-fsm-info request) :tokens) '(:input 100 :output 64000))
    (respond t)
    (should-not result)
    (cl-letf (((symbol-function 'gptel--handle-wait)
               (lambda (_) (ert-fail "Exhausted review dispatched another round"))))
      (gptel--fsm-transition request 'WAIT))
    (should (eq 'error (plist-get result :outcome)))
    (should (eq 'output-tokens (plist-get result :budget-kind)))
    (should (= 64000 (plist-get result :output-limit))))
  :doc "non-streaming reasoning overflow retains already available provider usage"
  (progn
    (start)
    (setf (plist-get (gptel-fsm-info request) :tokens) '(:input 200 :cached 100 :output 10000)
          (plist-get (gptel-fsm-info request) :stream) nil)
    (respond (cons 'reasoning (make-string 262145 ?r)))
    (should (eq 'output-bytes (plist-get result :budget-kind)))
    (should (= 200 (plist-get result :input-tokens)))
    (should (= 100 (plist-get result :cached-tokens)))
    (should (= 10000 (plist-get result :output-tokens)))
    (should (= 262145 (plist-get result :output-bytes)))
    (respond "late reply")
    (gptel--fsm-transition request 'DONE)
    (should (= 1 settlements)))
  :doc "an exactly exhausted byte budget refuses a followup even with tokens remaining"
  (let ((mevedel-memory-review-max-bytes 100))
    (start)
    (respond (make-string 100 ?x))
    (should-not result)
    (cl-letf (((symbol-function 'gptel--handle-wait)
               (lambda (_) (ert-fail "Byte-exhausted review dispatched another round"))))
      (gptel--fsm-transition request 'WAIT))
    (should (eq 'output-bytes (plist-get result :budget-kind)))
    (should (= 100 (plist-get result :output-limit)))
    (should (= 26 (plist-get result :output-estimated-tokens))))
  :doc "tool charges use the executable specification rather than raw JSON formatting"
  (let* ((raw (concat "{ " (make-string 1000 ?\s) "\"root\": \"workspace\", \"path\": \"source.el\" }"))
         (args (gptel--json-read-string raw))
         (normalized (decode-coding-string
                      (gptel--json-encode (vector (list :name "Read" :args args))) 'utf-8-unix)))
    (start)
    (setf (plist-get (gptel-fsm-info request) :tool-use) (list (list :name "Read" :args args)))
    (cl-letf (((symbol-function 'gptel--handle-tool-use) #'ignore))
      (gptel--fsm-transition request 'TOOL))
    (should-not result)
    (let ((snapshot (funcall (plist-get handle :usage))))
      (should (= (string-bytes normalized) (plist-get snapshot :output-bytes)))
      (should (= (string-bytes normalized) (plist-get snapshot :tool-call-bytes)))
      (should (< (plist-get snapshot :output-bytes) (string-bytes raw)))))
  :doc "transport failures without a response do not count completed rounds in either stream mode"
  (dolist (stream '(nil t))
    (setq result nil settlements 0)
    (start)
    (setf (plist-get (gptel-fsm-info request) :stream) stream
          (plist-get (gptel-fsm-info request) :error) "Connection failed")
    (respond nil)
    (gptel--fsm-transition request 'ERRS)
    (should (eq 'error (plist-get result :outcome)))
    (should (= 0 (plist-get result :rounds)))
    (should (= 1 settlements)))
  :doc "native reminder payloads are sparse, text-valued, and add no cache breakpoints"
  (dolist (kind '(openai anthropic bedrock))
    (setq result nil settlements 0)
    (let ((mevedel-memory-review-max-tokens 1000)
          (gptel-cache t))
      (put model :capabilities '(tool-use cache))
      (setq backend
            (pcase kind
              ('openai (gptel-make-openai "review-openai" :key "test-only" :models (list model)))
              ('anthropic (gptel-make-anthropic "review-anthropic" :key "test-only" :models (list model)))
              (_ (gptel-make-bedrock "review-bedrock" :region "us-east-1"
                                     :aws-bearer-token "test-only" :models (list model)))))
      (start)
      (ert-info ((format "%s: %S" kind result)) (should request) (should-not result))
      (cl-labels ((payload () (gptel--json-encode (plist-get (gptel-fsm-info request) :data)))
                  (occurrences (text) (1- (length (split-string (payload) text t)))))
        (let ((cache-count (occurrences "cache_control")))
          (when (eq kind 'anthropic) (should (> cache-count 0)))
          (cl-letf (((symbol-function 'gptel--handle-wait) #'ignore))
            (gptel--fsm-transition request 'WAIT)
            (should (= 0 (occurrences "Memory review budget reminder")))
            (dolist (row '((750 1 "250 output tokens") (0 1 "250 output tokens")
                           (150 2 "100 output tokens") (0 2 "100 output tokens")))
              (setf (plist-get (gptel-fsm-info request) :tokens) (list :output (car row)))
              (respond t)
              (gptel--fsm-transition request 'WAIT)
              (should-not result)
              (should (= (nth 1 row) (occurrences "Memory review budget reminder")))
              (should (string-match-p (nth 2 row) (payload)))
              (should (= cache-count (occurrences "cache_control"))))
            (should (string-match-p "Stop using tools" (payload)))
            (when (eq kind 'bedrock)
              (let* ((messages (plist-get (plist-get (gptel-fsm-info request) :data) :messages))
                     (content (plist-get (aref messages (1- (length messages))) :content)))
                (should (stringp (plist-get (aref content 0) :text)))))
          (with-current-buffer (plist-get handle :buffer)
            (should-not mevedel--session)
            (should (string-match-p "Memory review budget reminder (90%" (buffer-string))))))
      (funcall (plist-get handle :cancel)))))
  :doc "bytes, tools, results, and time independently trigger warnings and coalesce a jump"
  (dolist (kind '(bytes calls results time))
    (setq result nil settlements 0)
    (let ((now 1000.0) (mevedel-memory-review-max-bytes 1000))
      (cl-letf (((symbol-function 'float-time) (lambda (&optional _) now))
                ((symbol-function 'gptel--handle-wait) #'ignore))
        (start)
        (gptel--fsm-transition request 'WAIT)
        ;; Jump directly to 90%: only the most urgent stage should be emitted.
        (pcase kind
          ('bytes (respond (cons 'reasoning (make-string 900 ?r))))
          ('calls (setf (mevedel-memory-investigation-calls investigation) 58))
          ('results (setf (mevedel-memory-investigation-bytes investigation) 59000))
          ('time (setq now 1162.0)))
        (dotimes (_ 2) (gptel--fsm-transition request 'WAIT))
        (should-not result)
        (let ((text (gptel--json-encode (plist-get (gptel-fsm-info request) :data))))
          (should (= 2 (length (split-string text "Memory review budget reminder"))))
          (should (string-match-p "90% threshold" text))
          (should-not (string-match-p "75% threshold" text)))
        (funcall (plist-get handle :cancel)))))
  :doc "the input guard includes reminders and refuses dispatch when they exceed context"
  (progn
    (start)
    (cl-letf (((symbol-function 'gptel--handle-wait) #'ignore))
      (gptel--fsm-transition request 'WAIT))
    (setf (mevedel-memory-investigation-calls investigation) 58)
    (let ((real-tokens (symbol-function 'mevedel-memory-review--tokens)))
      (cl-letf (((symbol-function 'mevedel-memory-review--tokens)
                 (lambda (fsm)
                   (if (string-match-p "Memory review budget reminder"
                                       (gptel--json-encode (plist-get (gptel-fsm-info fsm) :data)))
                       1000000 (funcall real-tokens fsm))))
                ((symbol-function 'gptel--handle-wait)
                 (lambda (_) (ert-fail "Over-context reminder was dispatched"))))
        (gptel--fsm-transition request 'WAIT)))
    (should (eq 'error (plist-get result :outcome)))
    (should (equal "Review request exceeds usable input context" (plist-get result :error)))
    (should (= 1 settlements)))
  :doc "invalid configured budgets fail before dispatch without leaking the request"
  (dolist (invalid '(0 -1 nil 1.5))
    (let ((mevedel-memory-review-max-tokens invalid))
      (setq result nil sent nil)
      (start)
      (should-not sent)
      (should (eq 'error (plist-get result :outcome)))
      (should-not (buffer-live-p (plist-get handle :buffer))))))

(mevedel-deftest mevedel-memory-review-request/transport ()
  ,test
  (test)
  :doc "real Read and empty Glob rounds resume with results and validate only the final reply"
  (let* ((directory (make-temp-file "mevedel-memory-review-http-" t))
         (workspace (mevedel-workspace--create :root directory))
         (mevedel-memory-dirs nil)
         (gptel--known-backends nil)
         (gptel-confirm-tool-calls t)
         (gptel-use-curl t)
         (gptel-stream nil)
         (model (make-symbol "review-http"))
         (responses
          (list
           (list :choices
                 (vector (list :index 0 :finish_reason "tool_calls"
                               :message (list :role "assistant" :content "I will inspect the source."
                                              :tool_calls
                                              (vector (list :id "read-1" :type "function"
                                                            :function (list :name "Read"
                                                                            :arguments "{\"root\":\"workspace\",\"path\":\"source.el\"}"))))))
                 :usage '(:prompt_tokens 100 :completion_tokens 10 :total_tokens 110))
           (list :choices
                 (vector (list :index 0 :finish_reason "tool_calls"
                               :message (list :role "assistant" :content "I will check for stored evidence."
                                              :tool_calls
                                              (vector (list :id "glob-1" :type "function"
                                                            :function (list :name "Glob"
                                                                            :arguments "{\"root\":\"workspace\",\"path\":\".\",\"pattern\":\".mevedel/**\"}"))))))
                 :usage '(:prompt_tokens 200 :completion_tokens 20 :total_tokens 220))
           (list :choices (vector (list :index 0 :finish_reason "stop"
                                       :message (list :role "assistant" :content mevedel-test-memory-review--none)))
                 :usage '(:prompt_tokens 300 :completion_tokens 30 :total_tokens 330))))
         server children received result handle backend)
    (put model :context-window 128)
    (put model :capabilities '(tool-use))
    (unwind-protect
        (progn
          (with-temp-file (file-name-concat directory "source.el") (insert ";; Source evidence.\n"))
          (setq server
                (make-network-process
                 :name "memory-review-http" :server t :host 'local :service t
                 :family 'ipv4 :noquery t :coding 'binary :sentinel #'ignore
                 :filter
                 (lambda (process chunk)
                   (cl-pushnew process children)
                   (let ((text (concat (process-get process 'input) chunk)))
                     (process-put process 'input text)
                     (when (and (not (process-get process 'answered))
                                (string-match "\r\n\r\n" text))
                       (let* ((end (match-end 0))
                              (headers (substring text 0 end))
                              (case-fold-search t)
                              (length (and (string-match "Content-Length: *\\([0-9]+\\)" headers)
                                           (string-to-number (match-string 1 headers)))))
                         (when (and length (>= (- (length text) end) length))
                           (process-put process 'answered t)
                           (push (json-parse-string (substring text end (+ end length))
                                                   :object-type 'plist :array-type 'list) received)
                           (let ((body (gptel--json-encode (pop responses))))
                             (process-send-string
                              process (format "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: %s\r\nConnection: close\r\n\r\n%s"
                                              (string-bytes body) body))
                             (process-send-eof process)))))))))
          (setq backend (gptel-make-openai
                         "review-http" :key "test-only" :models (list model)
                         :protocol "http" :host (format "127.0.0.1:%s" (plist-get (process-contact server t) :service))
                         :curl-args '("--noproxy" "*")))
          (cl-letf (((symbol-function 'mevedel-model-resolve-workload)
                     (lambda (&rest _) (list :backend backend :model model))))
            (setq handle (mevedel-memory-review-request
                          (mevedel-memory-scope-capture workspace) nil
                          (lambda (value) (setq result value)) :memory-only t))
            (with-timeout (10 (ert-fail
                              (format "Review transport did not settle: %s requests, connections %S, active states %S"
                                      (length received)
                                      (mapcar #'process-status children)
                                      (mapcar (lambda (row) (list (gptel-fsm-state (cadr row))
                                                                  (plist-get (gptel-fsm-info (cadr row)) :error)))
                                              gptel--request-alist))))
              (while (not result) (accept-process-output nil 0.01))))
          (ert-info ((format "Review error: %s" (plist-get result :error)))
            (should (eq 'success (plist-get result :outcome))))
          (should (= 3 (length received)))
          (let ((limits (mapcar (lambda (data) (plist-get data :max_tokens)) (reverse received))))
            (should (= 64000 (car limits)))
            (should (> (nth 0 limits) (nth 1 limits) (nth 2 limits) 0)))
          (let ((tool-message (cl-find "tool" (plist-get (car received) :messages)
                                       :key (lambda (message) (plist-get message :role)) :test #'equal)))
            (should (string-match-p "Source evidence" (plist-get tool-message :content))))
          (should (seq-some
                   (lambda (message)
                     (and (equal "tool" (plist-get message :role))
                          (string-match-p "No files found matching pattern"
                                          (plist-get message :content))))
                   (plist-get (car received) :messages)))
          (should (= 600 (plist-get result :input-tokens)))
          (should (= 60 (plist-get result :output-tokens)))
          (should-not (buffer-live-p (plist-get handle :buffer))))
      (when handle
        (mevedel-test--with-captured-diagnostics nil (funcall (plist-get handle :cancel))))
      (dolist (process children) (when (process-live-p process) (delete-process process)))
      (when (process-live-p server) (delete-process server))
      (delete-directory directory t))))

(provide 'test-mevedel-memory-review)
;;; test-mevedel-memory-review.el ends here
