;;; test-mevedel-memory-pass.el -- Consolidation coordination -*- lexical-binding: t -*-

;;; Commentary:

;; Exercise candidate selection and pass settlement against real journal state.

;;; Code:

(require 'mevedel-journal-test-support
         (file-name-concat
          (file-name-directory
           (or buffer-file-name load-file-name byte-compile-current-file))
          "mevedel-journal-test-support"))
(require 'mevedel-journal-index)
(require 'mevedel-memory-pass)
(require 'gptel-openai)
(require 'mevedel-memory-store)
(require 'mevedel-memory-review)
(require 'mevedel-telemetry)

(defun mevedel-test-memory-pass--digest (workspace number session name)
  "Publish a dated test digest NUMBER for SESSION and NAME in WORKSPACE."
  (mevedel-journal-store-publish-digest
   (mevedel-workspace-root workspace)
   (list :capture-id (format "%064x" number) :session session :session-name name
         :workspace (mevedel-workspace-identity-read (mevedel-workspace-root workspace))
         :trigger 'session-end :segment 1 :source-revision (make-string 64 ?c)
         :turns '(1) :turn-ids (list (format "%064x" number))
         :created (format "2026-08-%02dT12:00:00Z" number) :model "test:model")
   "## Done\n- Observed: Tests passed.\n\n## Learned\n- none\n\n## Surprised\n- none\n\n## Unfinished\n- none"))

(mevedel-deftest mevedel-memory-pass-select ()
  ,test
  (test)
  :doc "general coverage is excluded while completed evidence from a live session remains eligible"
  (mevedel-test-journal-capture--with-session
   (lambda (session buffer)
     (mevedel-test-journal-capture--turn session buffer "Check source" "Tests passed")
     (let* ((workspace (mevedel-session-workspace session))
            (root (mevedel-workspace-root workspace))
            (first (mevedel-test-memory-pass--digest workspace 1 "closed-a" "A"))
            (live (mevedel-test-memory-pass--digest workspace 2 (mevedel-session-session-id session)
                                                   (mevedel-session-name session)))
            (third (mevedel-test-memory-pass--digest workspace 3 "closed-c" "C")))
       (mevedel-journal-store-publish-review
        root (list :pass-id (make-string 64 ?d) :workspace (mevedel-workspace-identity-read root)
                   :created "2026-08-04T12:00:00Z" :model "test:model" :focus ""
                   :digests (list (plist-get first :id)) :proposals nil :references nil))
       (let* ((entries (mevedel-journal-store-entries root))
              (selection (mevedel-memory-pass-select entries)))
         (should (equal (list live third) (plist-get selection :entries)))
         (should-not (plist-get selection :excluded))
         (should (= 2 (plist-get selection :eligible)))
         (should (= 0 (plist-get selection :remaining)))
         (should (equal (list first live third)
                        (plist-get (mevedel-memory-pass-select entries t) :entries)))
         (let ((mevedel-journal-enabled nil)) (kill-buffer buffer))
         (mevedel-session-persistence-lock-release (mevedel-session-save-path session) session)
         (should (equal (list live third)
                        (plist-get (mevedel-memory-pass-select entries) :entries)))
         (should (equal entries (mevedel-journal-store-entries root)))))))
  :doc "selection freezes twenty oldest digests and reports the remaining eligible backlog"
  (mevedel-test-journal-capture--with-session
   (lambda (session _buffer)
     (let* ((workspace (mevedel-session-workspace session))
            (root (mevedel-workspace-root workspace))
            published)
       (dotimes (index 24)
         (push (mevedel-test-memory-pass--digest workspace (1+ index) "closed" "Closed") published))
       (setq published (nreverse published))
       (let* ((entries (mevedel-journal-store-entries root))
              (selection (mevedel-memory-pass-select entries)))
         (should (equal (seq-take published 20) (plist-get selection :entries)))
         (should (= 24 (plist-get selection :eligible)))
         (should (= 4 (plist-get selection :remaining)))
         (should-not (plist-get selection :excluded))
         (mevedel-test-memory-pass--digest workspace 25 "arrived-later" "Later")
         (should (equal selection (mevedel-memory-pass-select entries)))
         (should (= 5 (plist-get (mevedel-memory-pass-select
                                 (mevedel-journal-store-entries root)) :remaining)))))))
  :doc "published evidence remains eligible without reading or changing source session locks"
  (mevedel-test-journal-capture--with-session
   (lambda (session buffer)
     (mevedel-test-journal-capture--turn session buffer "Check source" "Tests passed")
     (let* ((workspace (mevedel-session-workspace session))
            (root (mevedel-workspace-root workspace))
            (entry (mevedel-test-memory-pass--digest workspace 1 (mevedel-session-session-id session)
                                                    (mevedel-session-name session)))
            (lock (file-name-concat (mevedel-session-save-path session) ".lock")))
       (let ((mevedel-journal-enabled nil)) (kill-buffer buffer))
       (mevedel-session-persistence-lock-release (mevedel-session-save-path session) session)
       (dolist (contents (list "(:hostname \"another-host\" :pid 123)" "("
                              (format "(:hostname %S :pid nil)" (system-name))))
         (write-region contents nil lock nil 'silent)
         (let ((selection (mevedel-memory-pass-select (mevedel-journal-store-entries root))))
           (should (equal (list entry) (plist-get selection :entries)))
           (should (equal contents (mevedel-session-control-fs-read-file lock)))))
       (delete-file lock))))
  :doc "completed evidence from portable sessions remains eligible without changing their leases"
  (let ((local-root (file-name-as-directory (make-temp-file "mevedel-memory-live-" t))))
    (unwind-protect
        (mevedel-test--with-local-shell-tramp '("memory-live")
          (cl-destructuring-bind (workspace session directory _segment)
              (test-mevedel-session-persistence--make-remote-restore-fixture "memory-live" local-root "")
            (let* ((entry (mevedel-test-memory-pass--digest workspace 1 (mevedel-session-session-id session)
                                                          (mevedel-session-name session)))
                   (root (mevedel-workspace-root workspace))
                   (entries (mevedel-journal-store-entries root)))
              (dolist (owner (list (make-string 64 ?f) mevedel-session-durability--client-id))
                (unwind-protect
                    (progn
                      (let ((mevedel-session-durability--client-id owner))
                        (should (mevedel-session-durability-lease-acquire directory "Other conversation")))
                      (let* ((before (mevedel-session-durability-lease-status directory))
                             (selection (mevedel-memory-pass-select entries)))
                        (should (equal (list entry) (plist-get selection :entries)))
                        (should (equal before (mevedel-session-durability-lease-status directory)))))
                  (let ((mevedel-session-durability--client-id owner))
                    (mevedel-session-durability-lease-release directory))))
              (should (equal (list entry) (plist-get (mevedel-memory-pass-select entries) :entries))))))
      (delete-directory local-root t)
      (mevedel-workspace-clear-registry)))
  :doc "an independent Emacs holder can continue while its completed evidence is selected"
  (mevedel-test-journal-capture--with-session
   (lambda (session buffer)
     (mevedel-test-journal-capture--turn session buffer "Check source" "Tests passed")
     (let* ((workspace (mevedel-session-workspace session))
            (root (mevedel-workspace-root workspace))
            (directory (mevedel-session-save-path session))
            (entry (mevedel-test-memory-pass--digest workspace 1 (mevedel-session-session-id session)
                                                    (mevedel-session-name session)))
            (runner (file-name-concat root "holder.el"))
            (ready (file-name-concat root "ready"))
            (release (file-name-concat root "release"))
            (output (generate-new-buffer " *memory-holder*"))
            process)
       (unwind-protect
           (progn
             (let ((mevedel-journal-enabled nil)) (kill-buffer buffer))
             (mevedel-session-persistence-lock-release directory session)
             (with-temp-file runner
               (insert ";;; -*- lexical-binding: t -*-\n")
               (prin1
                `(progn
                   (setq load-path ',load-path)
                   (require 'mevedel-structs)
                   (require 'mevedel-session-persistence)
                   (let ((owner (mevedel-session--create
                                 :workspace (mevedel-workspace--create :type 'file :root ,root)
                                 :authority-mode 'pid-lock))
                         (deadline (+ (float-time) 15)))
                     (unwind-protect
                         (progn
                           (unless (mevedel-session-persistence-lock-acquire ,directory "Independent holder" owner)
                             (error "Could not acquire test session"))
                           (write-region "ready" nil ,ready nil 'silent)
                           (while (and (not (file-exists-p ,release)) (< (float-time) deadline))
                             (accept-process-output nil 0.01)))
                       (mevedel-session-persistence-lock-release ,directory owner))))
                (current-buffer)))
             (setq process (make-process :name "memory-independent-holder" :buffer output :noquery t
                                         :sentinel #'ignore
                                         :command (list (file-name-concat invocation-directory invocation-name)
                                                        "-Q" "--batch" "-l" runner)))
             (with-timeout (10 (ert-fail "Independent holder did not acquire authority"))
               (while (and (process-live-p process) (not (file-exists-p ready)))
                 (accept-process-output nil 0.01)))
             (ert-info ((with-current-buffer output (buffer-string)))
               (should (file-exists-p ready))
               (should (process-live-p process)))
             (let ((selection (mevedel-memory-pass-select (mevedel-journal-store-entries root))))
               (should (equal (list entry) (plist-get selection :entries))))
             (write-region "release" nil release nil 'silent)
             (with-timeout (10 (ert-fail "Independent holder did not release authority"))
               (while (process-live-p process) (accept-process-output nil 0.01)))
             (should (= 0 (process-exit-status process)))
             (should (equal (list entry)
                            (plist-get (mevedel-memory-pass-select (mevedel-journal-store-entries root)) :entries))))
         (when (process-live-p process) (delete-process process))
         (kill-buffer output))))))

(mevedel-deftest mevedel-memory-pass-start
    (:vars* ((directory (make-temp-file "mevedel-memory-coordinator-" t))
             (workspace (mevedel-workspace--create :root directory))
             (identity (mevedel-workspace-identity-ensure directory))
             (mevedel-memory-dirs nil)
             (mevedel-memory-consolidation-mode 'manual)
             (gptel--known-backends nil)
             (model (make-symbol "review-model"))
             (backend (gptel-make-openai "coordinator-test" :key "test-only" :models (list model)))
             (real-request (symbol-function 'gptel-request))
             (none "## Promote\n- none\n## Update\n- none\n## Merge\n- none\n## Remove\n- none\n## Instructions\n- none\n## No action\n- No supported changes.")
             (settlements 0) request provider state result)
     :before-each ((put model :context-window 128) (put model :capabilities '(tool-use)))
     :after-each ((mevedel-memory-pass-cancel workspace) (delete-directory directory t)))
  (cl-letf (((symbol-function 'mevedel-model-resolve-workload)
             (lambda (&rest _) (list :backend backend :model model)))
            ((symbol-function 'gptel-request)
             (lambda (prompt &rest args)
               (let ((fsm (apply real-request prompt (plist-put (copy-sequence args) :dry-run t))))
                 (unless (plist-get args :dry-run)
                   (setq request fsm provider (plist-get args :callback)))
                 fsm))))
    (cl-labels ((start (&rest options)
                  (setq state (apply #'mevedel-memory-pass-start workspace
                                     (lambda (value) (cl-incf settlements) (setq result value)) options)))
                (finish (text)
                  (funcall provider text (gptel-fsm-info request))
                  (gptel--fsm-transition request 'DONE))
                (events ()
                  (with-temp-buffer
                    (insert-file-contents
                     (file-name-concat directory ".mevedel" "diagnostics" mevedel-telemetry-file-name))
                    (goto-char (point-min))
                    (let (values)
                      (condition-case nil
                          (while t (push (read (current-buffer)) values))
                        (end-of-file (nreverse values)))))))
      ,test))
  (test)
  :doc "telemetry reports focused review counts and usage without private focus or content"
  (progn
    (mevedel-test-memory-pass--digest workspace 1 "closed" "Closed")
    (start :focus "SECRET focus")
    (setf (plist-get (gptel-fsm-info request) :tokens) '(:input 11 :cached 3 :output 5)
          (plist-get (gptel-fsm-info request) :stream) nil)
    (finish none)
    (let* ((records (events)) (completed (cadr records)))
      (should (equal '(memory-consolidation-fired memory-consolidation-completed)
                     (mapcar (lambda (event) (plist-get event :event)) records)))
      (should (eq 'focused (plist-get completed :scope)))
      (should (eq 'manual (plist-get completed :mode)))
      (should (= 1 (plist-get completed :reviewed-count)))
      (should (= 0 (plist-get completed :covered-count)))
      (should (= 0 (plist-get completed :proposed-count)))
      (should (= 11 (plist-get completed :input-tokens)))
      (should (= 3 (plist-get completed :cached-tokens)))
      (should (= 5 (plist-get completed :output-tokens)))
      (should (equal (plist-get (plist-get state :claim) :owner) (plist-get completed :pass-id)))
      (should (numberp (plist-get completed :duration-ms)))
      (should-not (plist-get completed :dropped-keys))
      (should-not (string-match-p "SECRET\\|test-only\\|No supported changes" (prin1-to-string records)))))
  :doc "telemetry retains reported usage and unconsumed backlog on cancellation without duplicate late events"
  (progn
    (mevedel-test-memory-pass--digest workspace 1 "closed" "Closed")
    (start)
    (setf (plist-get (gptel-fsm-info request) :tokens) '(:input 17 :cached 2 :output 4)
          (plist-get (gptel-fsm-info request) :stream) nil)
    (funcall provider "SECRET partial response" (gptel-fsm-info request))
    (mevedel-memory-pass-cancel workspace)
    (finish none)
    (let* ((records (events)) (killed (cadr records)))
      (should (equal '(memory-consolidation-fired memory-consolidation-killed)
                     (mapcar (lambda (event) (plist-get event :event)) records)))
      (should (= 17 (plist-get killed :input-tokens)))
      (should (= 4 (plist-get killed :output-tokens)))
      (should (= 1 (plist-get killed :remaining-count)))
      (should (= 0 (plist-get killed :covered-count)))
      (should (= 1 (plist-get result :remaining)))
      (should-not (string-match-p "SECRET" (prin1-to-string records)))))
  :doc "telemetry preserves provider usage when accepting a valid result fails on disk"
  (progn
    (mevedel-test-memory-pass--digest workspace 1 "closed" "Closed")
    (start)
    (make-directory (file-name-concat
                     (mevedel-memory-store--directory workspace (plist-get (plist-get state :claim) :owner))
                     "accepted.el"))
    (setf (plist-get (gptel-fsm-info request) :tokens) '(:input 19 :cached 0 :output 6)
          (plist-get (gptel-fsm-info request) :stream) nil)
    (finish none)
    (let* ((records (events)) (failed (cadr records)))
      (should (equal '(memory-consolidation-fired memory-consolidation-failed)
                     (mapcar (lambda (event) (plist-get event :event)) records)))
      (should (= 19 (plist-get failed :input-tokens)))
      (should (= 6 (plist-get result :output-tokens)))
      (should (= 1 (plist-get failed :remaining-count)))
      (should (= 0 (plist-get failed :covered-count)))
      (should (eq 'publication (plist-get failed :failure-class)))
      (should-not (plist-member failed :error))))
  :doc "publishes one complete batch only after success and leaves a later arrival unreviewed"
  (let ((first (mevedel-test-memory-pass--digest workspace 1 "closed" "Closed")))
    (start)
    (should (eq state (mevedel-memory-pass-running workspace)))
    (should (= 1 (length (mevedel-journal-index-unreviewed (mevedel-journal-store-entries directory)))))
    (with-current-buffer (plist-get (plist-get state :request) :buffer) (should-not mevedel--session))
    (should-error (mevedel-memory-pass-start workspace #'ignore))
    (let ((later (mevedel-test-memory-pass--digest workspace 2 "later" "Later")))
      (finish none)
      (should (= settlements 1))
      (should (eq 'success (plist-get result :outcome)))
      (should (equal (list (plist-get first :id)) (plist-get (plist-get result :entry) :digests)))
      (should (equal (list later) (mevedel-journal-index-unreviewed (mevedel-journal-store-entries directory)))))
    (should-not (mevedel-memory-pass-running workspace))
    (should-not (timerp (plist-get state :timer))))
  :doc "cancellation fences a late callback while a successor remains live"
  (progn
    (mevedel-test-memory-pass--digest workspace 1 "closed" "Closed")
    (start)
    (let ((old-provider provider) (old-request request) (old-claim (plist-get state :claim)))
      (should (mevedel-memory-pass-cancel workspace))
      (should (eq 'cancelled (plist-get (mevedel-journal-claim-outcome old-claim) :status)))
      (should (eq 'aborted (plist-get result :outcome)))
      (start)
      (funcall old-provider none (gptel-fsm-info old-request))
      (gptel--fsm-transition old-request 'DONE)
      (should (= settlements 1))
      (should (eq state (mevedel-memory-pass-running workspace)))
      (should-not (mevedel-journal-claim-outcome (plist-get state :claim)))
      (finish none)
      (should (= settlements 2))
      (should-not (mevedel-journal-index-unreviewed (mevedel-journal-store-entries directory)))))
  :doc "malformed output consumes no coverage and a later request may retry"
  (progn
    (mevedel-test-memory-pass--digest workspace 1 "closed" "Closed")
    (start)
    (setf (plist-get (gptel-fsm-info request) :tokens) '(:input 23 :cached 1 :output 3)
          (plist-get (gptel-fsm-info request) :stream) nil)
    (finish "SECRET invalid review")
    (should (eq 'error (plist-get result :outcome)))
    (let ((failed (cadr (events))))
      (should (eq 'memory-consolidation-failed (plist-get failed :event)))
      (should (eq 'review (plist-get failed :failure-class)))
      (should (= 23 (plist-get failed :input-tokens)))
      (should (= 1 (plist-get failed :remaining-count)))
      (should-not (string-match-p "SECRET" (prin1-to-string failed))))
    (should (eq 'failed (plist-get (mevedel-journal-claim-outcome (plist-get state :claim)) :status)))
    (should (= 1 (length (mevedel-journal-index-unreviewed (mevedel-journal-store-entries directory)))))
    (start)
    (finish none)
    (should (eq 'success (plist-get result :outcome))))
  :doc "explicit empty and focused passes do not consume general review evidence"
  (progn
    (start :memory-only t)
    (finish none)
    (should (eq 'success (plist-get result :outcome)))
    (should-not (plist-get (plist-get result :entry) :digests))
    (mevedel-test-memory-pass--digest workspace 1 "closed" "Closed")
    (start :focus "Test conditions")
    (finish none)
    (should (eq 'success (plist-get result :outcome)))
    (should (= 1 (length (mevedel-journal-index-unreviewed (mevedel-journal-store-entries directory))))))
  :doc "closing the running inspection buffer cancels and retires the local pass"
  (progn
    (mevedel-test-memory-pass--digest workspace 1 "closed" "Closed")
    (start)
    (kill-buffer (plist-get (plist-get state :request) :buffer))
    (should (eq 'aborted (plist-get result :outcome)))
    (should (= settlements 1))
    (should-not (mevedel-memory-pass-running workspace))
    (should (eq 'cancelled (plist-get (mevedel-journal-claim-outcome (plist-get state :claim)) :status)))
    (should (= 1 (length (mevedel-journal-index-unreviewed (mevedel-journal-store-entries directory))))))
  :doc "recovers an accepted result before selecting a successor batch"
  (let* ((entry (mevedel-test-memory-pass--digest workspace 1 "closed" "Closed"))
         (claim (mevedel-journal-claim-acquire (mevedel-memory-store--claim-directory workspace) 180))
         (prepared (mevedel-memory-store-prepare workspace claim (mevedel-memory-scope-capture workspace) (list entry) "")))
    (mevedel-memory-store-accept workspace prepared none (list entry) "test:model" nil)
    (should (= 1 (length (mevedel-journal-store-entries directory))))
    (start :memory-only t)
    (should-not (plist-get (plist-get state :prepared) :entries))
    (should-not (mevedel-journal-index-unreviewed (mevedel-journal-store-entries directory)))
    (finish none)
    (should (= 3 (length (mevedel-journal-store-entries directory))))))

(mevedel-deftest mevedel-memory-pass--finish ()
  ,test
  (test)
  :doc "an expired owner's late success cannot publish or alter its successor's evidence pins"
  (let* ((directory (make-temp-file "mevedel-memory-expired-owner-" t))
         (workspace (mevedel-workspace--create :root directory))
         (identity (mevedel-workspace-identity-ensure directory))
         (mevedel-memory-dirs nil)
         (gptel--known-backends nil)
         (backend (gptel-make-openai "expired-test" :key "test-only" :models '(test-model)))
         (entry (mevedel-test-memory-pass--digest workspace 1 "closed" "Closed"))
         (scope (mevedel-memory-scope-capture workspace))
         (key (mevedel-memory-store--claim-directory workspace))
         (claim (mevedel-journal-claim-acquire key 2))
         (prepared (mevedel-memory-store-prepare workspace claim scope (list entry) ""))
         (state (list :workspace workspace :claim claim :prepared prepared :settled nil))
         successor)
    (unwind-protect
        (progn
          (while (< (mevedel-session-control-fs-target-time key) (plist-get claim :expires-at))
            (accept-process-output nil 0.05))
          (setq successor (mevedel-journal-claim-acquire key 180))
          (should successor)
          (let* ((next (mevedel-memory-store-prepare workspace successor scope (list entry) ""))
                 (pin (mevedel-memory-store--pin workspace (plist-get successor :owner) (plist-get entry :id))))
            (mevedel-memory-pass--finish
             state (list :outcome 'success :entries (list entry) :policy (list :backend backend :model 'test-model)
                         :reply "## Promote\n- none\n## Update\n- none\n## Merge\n- none\n## Remove\n- none\n## Instructions\n- none\n## No action\n- No changes."))
            (should (eq 'error (plist-get (plist-get state :result) :outcome)))
            (should (eq 'expired (plist-get (mevedel-journal-claim-outcome claim) :status)))
            (should-not (mevedel-journal-claim-outcome successor))
            (should (equal successor (mevedel-journal-claim-current key)))
            (should (equal (plist-get next :hash) (mevedel-session-control-fs-read-file pin)))
            (should-not (file-exists-p (mevedel-memory-store--pin workspace (plist-get claim :owner) (plist-get entry :id))))
            (should (equal (list entry) (mevedel-journal-index-unreviewed (mevedel-journal-store-entries directory))))))
      (when successor (mevedel-journal-claim-settle successor 'cancelled ""))
      (delete-directory directory t))))

(provide 'test-mevedel-memory-pass)
;;; test-mevedel-memory-pass.el ends here
