;;; test-mevedel-collaboration-recovery.el --- Recovery authority -*- lexical-binding: t -*-
;;; Commentary:
;; Login and repair frames have the same explicit owner boundary.
;;; Code:
(require 'helpers (file-name-concat (file-name-directory (or load-file-name buffer-file-name)) "helpers"))
(require 'mevedel-collaboration-recovery)
(require 'mevedel-collaboration)
(require 'mevedel-engine-test-support
         (file-name-concat (file-name-directory (or load-file-name buffer-file-name)) "mevedel-engine-test-support"))

(mevedel-deftest mevedel-collaboration-recovery-handle (:quiet t)
  ,test
  (test)
  :doc "ordinary guests cannot change recovery state"
  (let* ((guests (make-hash-table :test #'eql))
	 (room (list :guests guests)))
    (puthash 1 '(:writable t :owner nil) guests)
    (dolist (action '("model" "preset" "history" "retry" "login" "login-code" "cancel-login" "update" "input-discard"))
      (should-error (mevedel-collaboration-recovery-handle room 1 (list :action action)) :type 'user-error)))
  :doc "owner requeue discards failed live preparation and keeps input provenance"
  (mevedel-engine-test--with-session
    (mevedel-request-end)
    (let* ((submission (mevedel-prompt-submission-create :input "fresh" :session session :state 'reserved))
           (entry (list :id 1 :category 'steering :state 'failed-turn :input "fresh"
                        :guest-name "Owner" :request-id "old" :submission submission
                        :request-context '(:old t)))
           (guests (make-hash-table :test #'eql))
           (room (list :session session :data-buffer buffer :guests guests)))
      (puthash 1 '(:owner t :writable t) guests)
      (setf (mevedel-session-pending-steering session) (list entry)
            (mevedel-session-pending-input-next-id session) 1
            (mevedel-session-pending-input-failure-paused session) t)
      (cl-letf (((symbol-function 'mevedel-collaboration--publish-status) #'ignore)
                ((symbol-function 'mevedel-collaboration--publish-queue) #'ignore)
                ((symbol-function 'mevedel-collaboration-recovery-send) #'ignore))
        (mevedel-collaboration-recovery-handle room 1 '(:action "input-requeue" :value 1)))
      (let ((queued (car (mevedel-session-pending-follow-ups session))))
        (should (equal "fresh" (plist-get queued :input)))
        (should (equal "Owner" (plist-get queued :guest-name)))
        (should-not (plist-get queued :submission))
        (should-not (plist-get queued :request-context))
        (should-not (plist-get queued :request-id))
        (should-not (mevedel-session-pending-steering session))
        (should (mevedel-session-pending-input-failure-paused session))))))

(mevedel-deftest mevedel-collaboration-recovery-send ()
  ,test
  (test)
  :doc "ordinary guests receive no recovery state"
  (let ((room (list :guests (make-hash-table :test #'eql))) sent)
    (cl-letf (((symbol-function 'mevedel-collaboration--transport-send)
               (lambda (&rest _) (setq sent t))))
      (mevedel-collaboration-recovery-send room 1)
      (should-not sent)))
  :doc "live queue and request updates expose new recovery choices only to owners"
  (mevedel-engine-test--with-session
    (mevedel-request-end)
    (let* ((guests (make-hash-table :test #'eql))
           (room (list :session session :data-buffer buffer :guests guests))
           (mevedel-collaboration--rooms (make-hash-table :test #'eq))
           (model-candidates (symbol-function 'mevedel-model-candidates))
           (model-reads 0)
           (runtime-reads 0)
           sent)
      (puthash buffer room mevedel-collaboration--rooms)
      (puthash 1 (list :owner t :writable t :ready t) guests)
      (puthash 2 (list :owner nil :writable t :ready t) guests)
      (cl-letf (((symbol-function 'mevedel-collaboration--transport-send)
                 (lambda (_transport peer frame) (push (cons peer frame) sent) t))
                ((symbol-function 'mevedel-collaboration--transport-control) #'ignore)
                ((symbol-function 'mevedel-model-candidates)
                 (lambda () (cl-incf model-reads) (funcall model-candidates)))
                ((symbol-function 'mevedel-claude-code-maintenance-state)
                 (lambda () (cl-incf runtime-reads) nil)))
        (mevedel-collaboration-recovery-send room 1)
        (setq sent nil)
        (setf (mevedel-session-pending-steering session)
              (list (list :id 1 :category 'steering :state 'failed-turn :input "retained")))
        (mevedel-collaboration-notify-queue-changed session)
        (let ((frames (cl-remove-if-not
                       (lambda (entry) (equal "recovery" (plist-get (cdr entry) :t))) sent)))
          (should (= 1 (length frames)))
          (should (= 1 (caar frames)))
          (should (equal "retained" (plist-get (aref (plist-get (cdar frames) :steering) 0) :text))))
        (setq sent nil)
        (mevedel-collaboration-notify-queue-changed session)
        (should-not sent)
        (setf (mevedel-session-external-conversations session)
              (list (cons "root" (list :native-session-id "fixture"))))
        (mevedel-recovery-report session "history" 'history "Recover history" t)
        (let ((frames (cl-remove-if-not
                       (lambda (entry) (equal "recovery" (plist-get (cdr entry) :t))) sent)))
          (should (= 1 (length frames)))
          (should (equal ["root"] (plist-get (cdar frames) :histories))))
        (should (= runtime-reads 1))
        (setq sent nil)
        (let ((before model-reads))
          (dotimes (_ 20) (mevedel-collaboration--publish-status room))
          (should (= before model-reads))
          (should-not sent))
        (mevedel-collaboration-recovery-runtime-changed '(:status "ready" :message "Updated"))
        (should (= runtime-reads 1))
        (should (equal "Updated" (plist-get (plist-get (cdar sent) :runtime) :message)))))))

(mevedel-deftest mevedel-collaboration-recovery-auth-changed
  (:doc "authentication changes refresh only owners viewing that credential store")
  (let* ((gptel--known-backends nil)
         (codex (gptel-make-openai-oauth "Recovery Codex"))
         (claude (mevedel-claude-code-register))
         (first (generate-new-buffer " *recovery-codex*"))
         (second (generate-new-buffer " *recovery-claude*"))
         (mevedel-collaboration--rooms (make-hash-table :test #'eq))
         (first-guests (make-hash-table :test #'eql))
         (second-guests (make-hash-table :test #'eql))
         sent)
    (unwind-protect
        (progn
          (with-current-buffer first (setq-local gptel-backend codex))
          (with-current-buffer second (setq-local gptel-backend claude))
          (puthash 1 (list :owner t :writable t) first-guests)
          (puthash 2 (list :owner t :writable t :recovery-backend codex) second-guests)
          (puthash 3 (list :owner t :writable t) second-guests)
          (puthash first (list :data-buffer first :guests first-guests) mevedel-collaboration--rooms)
          (puthash second (list :data-buffer second :guests second-guests) mevedel-collaboration--rooms)
          (cl-letf (((symbol-function 'mevedel-collaboration-recovery-send)
                     (lambda (_room peer) (push peer sent))))
            (mevedel-collaboration-recovery-auth-changed claude nil)
            (should (equal '(3) sent))
            (setq sent nil)
            (mevedel-collaboration-recovery-auth-changed codex nil)
            (should (equal '(1 2) (sort sent #'<)))
            (should (eq codex (plist-get (gethash 2 second-guests) :recovery-backend)))
            (should-not (plist-get (gethash 1 first-guests) :recovery-backend))))
      (kill-buffer first)
      (kill-buffer second))))

(provide 'test-mevedel-collaboration-recovery)
;;; test-mevedel-collaboration-recovery.el ends here
