;; -*- mode: eask; lexical-binding: t -*-

(package "mevedel"
         "0.5.0"
         "Instructed LLM programmer/assistant")

(website-url "https://github.com/FrauH0lle/mevedel")
(keywords "convenience" "tools" "llm" "gptel" "gptel-agent")

(package-file "mevedel.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "30.1")
(depends-on "gptel-agent")
