;;; lab.el --- Isolated renderer experiment -*- lexical-binding: t -*-
(require 'server)
(require 'mevedel-view-animation)
(setq inhibit-startup-screen t
      server-name (getenv "MEVEDEL_LAB_SERVER")
      frame-title-format "mevedel animation experiment")
(server-start)
(blink-cursor-mode -1)
(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
(set-frame-font "Aporetic Serif Mono-16" nil t)
(switch-to-buffer "Animation experiment")
(insert "Isolated animation experiment. This window closes automatically.\n\n")
(defvar lab-start (point))
(insert "Working...")
(defvar lab-end (point))
(insert "\n\nThe label above uses mevedel's prepared animation frames.\n")
(setq cursor-type nil)
(when (getenv "MEVEDEL_GTK_PROBE")
  (module-load (getenv "MEVEDEL_GTK_PROBE")))
(declare-function lab-gtk-mode "gtk-probe" (mode x y milliseconds))
(when (getenv "MEVEDEL_CANVAS_PROBE")
  (module-load (getenv "MEVEDEL_CANVAS_PROBE")))
(declare-function lab-canvas-draw "canvas-probe" (canvas seconds))
(declare-function canvas-refresh "image.c" (canvas))
(defvar lab-canvas '(image :type canvas :data-width 400 :data-height 64 :scale 0.5))
(defvar mevedel-view-native--load-state)
(declare-function mevedel-view-native-sync "mevedel-view-native" (specs elapsed rearm))
(declare-function mevedel-view-native-stop "mevedel-view-native" ())
(when (getenv "MEVEDEL_NATIVE_MODULE")
  (require 'mevedel-view-native)
  (module-load (getenv "MEVEDEL_NATIVE_MODULE"))
  (setq mevedel-view-native--load-state 'ready))
(defvar lab-style (intern (or (getenv "MEVEDEL_LAB_STYLE") "bounce")))
(defvar lab-target (cons (copy-marker lab-start) (copy-marker lab-end)))
(defvar lab-timer nil)
(defvar lab-calls 0)
(defvar lab-mode nil)
(defvar lab-rate 30.0)
(defvar lab-start-time 0.0)
(defun lab-tick ()
  (cl-incf lab-calls)
  (when (equal lab-mode "canvas")
    (lab-canvas-draw lab-canvas (- (float-time) lab-start-time))
    (canvas-refresh lab-canvas))
  (when (equal lab-mode "text")
    (let ((sample (mevedel-view-animation-frame
                   lab-style "Working..." (- (float-time) lab-start-time)
                   'default)))
      (with-current-buffer "Animation experiment"
        (with-silent-modifications
          (put-text-property lab-start lab-end 'display sample))))))
(defun lab-native-rearm ()
  (when (equal lab-mode "native-owned")
    (with-current-buffer "Animation experiment"
      (mevedel-view-native-sync
       (list (list lab-target lab-style "Working..." 'default (/ 1.0 lab-rate)))
       (- (float-time) lab-start-time) #'lab-native-rearm))))
(defun lab-set (mode rate)
  (when (timerp lab-timer) (cancel-timer lab-timer))
  (when (fboundp 'mevedel-view-native-stop)
    (with-current-buffer "Animation experiment" (mevedel-view-native-stop)))
  (when (fboundp 'lab-gtk-mode)
    (let* ((window (get-buffer-window "Animation experiment"))
           (position (posn-at-point lab-start window))
           (xy (posn-x-y position))
           (edges (window-inside-pixel-edges window)))
      (lab-gtk-mode (cond ((equal mode "single") 1)
                          ((equal mode "app-paintable") 2)
                          ((equal mode "native-noop") 3)
                          ((equal mode "native-widget") 4)
                          ((equal mode "native-surface") 5) (t 0))
                    (+ (car edges) (car xy))
                    (+ (cadr edges) (cdr xy))
                    (round (/ 1000 rate)))))
  (setq lab-mode (if (member mode '("single" "app-paintable")) "text" mode)
        lab-rate rate lab-calls 0
        lab-timer nil lab-start-time (float-time))
  (with-current-buffer "Animation experiment"
    (remove-text-properties lab-start lab-end '(display nil))
    (when (equal mode "canvas")
      (put-text-property lab-start lab-end 'display lab-canvas)))
  (mevedel-view-animation-frame lab-style "Working..." 0 'default)
  (when (equal mode "native-owned")
    (with-current-buffer "Animation experiment"
      (put-text-property lab-start lab-end 'display
                         (mevedel-view-animation-frame lab-style "Working..." 0 'default)))
    (redisplay t)
    (lab-native-rearm))
  (unless (member mode '("idle" "native-noop" "native-widget" "native-surface" "native-owned"))
    (setq lab-timer (run-at-time 0 (/ 1.0 rate) #'lab-tick)))
  t)
(set-frame-size nil 1536 888 t)
(provide 'lab)
